project 'UserInfoFetcherExample.xcodeproj'

platform :ios, '9.0'

target 'UserInfoFetcherExample' do
  use_frameworks!

  pod 'BandyerSDK', :git => 'https://github.com/Bandyer/Bandyer-iOS-SDK.git'
end
