project 'Bandyer-iOS-SDK-Basic-Example-ObjC.xcodeproj'

# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'Bandyer-iOS-SDK-Basic-Example-ObjC' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for Bandyer-iOS-SDK-Basic-Example-ObjC

  pod 'BandyerSDK', :git => 'https://github.com/Bandyer/Bandyer-iOS-SDK.git'
end
