project 'ChatExample.xcodeproj'

platform :ios, '9.0'

target 'ChatExample' do
  use_frameworks!

  pod 'BandyerSDK', :git => 'https://github.com/Bandyer/Bandyer-iOS-SDK.git', :tag => '1.2.0-beta'
end
